name: NGINX CI

on:
  push:
    branches: [ master ]

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: |
          docker build -t sickwick/nginx:prod nginx/
          docker run -d -p 80:80 sickwick/nginx:prod
          
  deploy:
      needs: [build-docker]
      runs-on: ubuntu-latest
      name: Deploy

      steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: sickwick/nginx:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          context: ./nginx

      - name: Pull image to the server
        run: |
          curl ${{ secrets.PULL_NGINX }}
          
  build-client:
    runs-on: ubuntu-latest
    name: Client
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
   
    - name: build
      run: |
        cd client
        npm i
        docker build -t sickwick/main-site:prod .
        docker run -d -p 4200:4200 sickwick/main-site:prod
        
    - name: Publish container
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sickwick/main-site:latest
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        context: ./client
    - name: Pull image
      run: |
        curl ${{ secrets.PULL_CLIENT }}
